name: First Workflow
on: [push]

jobs:
    docker-job:
        runs-on: ubuntu-latest
        container:
          image: node:20.3-alpine3.17
        steps:
            - name: echo a string
              run: |
                node -v
              