name: First Workflow
on: [push]

jobs:
    run-commands:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              env:
                ENVEE: Monday
              run: echo "$ENVEE"
            - name: Multiline Command
              uses: actions/checkout@v4
            - run: ls -a