name: First Workflow
on: 
  pull_request:
    branches:
       - main
jobs:
    danger-js:
      name: danger js
      runs-on: ubuntu-latest
      permissions: 
        pull-requests: write
        issues: write
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: "20"
        - name: install yarn
          run: npm i -g yarn
        - name: install dependency
          run: yarn
        - name: Danger
          uses: danger/danger-js@12.3.3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DANGER_DISABLE_TRANSPILATION: true
