name: First Workflow
on: 
  push:
  

jobs:
    danger-js:
      name: danger js
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Danger
          uses: danger/danger-js@11.0.2
          env:
            # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DANGER_DISABLE_TRANSPILATION: true